openapi: 3.0.0
info:
  title: Banchango-Api.v3
  version: '3.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  responses: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: Bearer Token 값입니다. JWT Token을 사용합니다.
