version: '3'
services:
        wherehouse-api:
                build: 
                        context: ..
                        dockerfile: ops/wherehouse-api/Dockerfile
                ports:
                        - "127.0.0.1:3000:3000"
                depends_on:
                        - mysql
        mysql:
                build: mysql
                volumes:
                        - mysql_data:/var/lib/mysql
                ports:
                        - "127.0.0.1:3306:3306"
volumes:
        mysql_data:
