FROM mysql:5.7

COPY mysqld_charset.cnf /etc/mysql/conf.d/mysqld_charset.cnf

EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=wherehouse
ENV MYSQL_PASSWORD=group
ENV MYSQL_DATABASE=wherehouse

