name: Wherehouse Backend CI

on:
  push:
    branches: [ master, develop, feature/*, fix/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: source ops/.test_env && cd ops && docker-compose down -v && cd .. && ./test_start.sh && sleep 20 && docker exec ops_wherehouse-api_1 npm run test

