name: Wherehouse Backend CI

on:
  push:
    branches: [ master, develop, feature/*, fix/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: source ops/.test_env && ./start.sh && docker exec ops_wherehouse-api_1 npm run test && docker ps && docker container ls -a
